flaskproject/src/ext/login/__init__.py
from flask_login import LoginManager
from src.ext.auth.models import User

login_manager = LoginManager()

def init_app(app):
    login_manager.init_app(app)
    login_manager.login_view = 'login'

@login_manager.user_loader
def load_user(id):
    return User.query.filter_by(id=id).first()

flaskproject/src/ext/site/main.py
import re
from flask import flash, jsonify, render_template
from flask import Blueprint
from flask import current_app as app
from flask import request
from flask import redirect, url_for
from flask_login import login_user, logout_user
from src.ext.auth.form import UserForm
from src.ext.auth.form import LoginForm
from src.ext.site.controllers import get_items
from src.ext.auth.models import User
from src.ext.auth.controller import create_user, save_user_foto
import json
import decimal
from collections import defaultdict

bp = Blueprint("site", __name__)


@bp.route("/")
def index():
    # current_app.logger.debug("entrei na função main") << ferramenta de debug para o toolbar
    return render_template("index.html", get_item=get_items())


@bp.route("/sobre")
def about():
    return render_template("about.html")


@bp.route("/cadastro", methods=["GET", "POST"])
def signup():
    form = UserForm()
    if form.validate_on_submit():
        create_user(
            email=form.email.data,
            password=form.password.data
        )
        foto = request.files.get('foto')
        if foto:
            save_user_foto(
                foto.filename,
                foto
            )

        # TODO forçar login
        return redirect("/")

    return render_template("userform.html", form=form)


@bp.route("/lanches")
def lanches():
    get_item = get_items()
    return render_template("lanches.html", get_item=get_item)


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        login_user(user)
        if user and user.passwd == form.password.data:
            flash('Logged in.')
            return redirect("/")
        else:
            flash('Invalid Login.')
    else:
        print(form.errors)

    return render_template("loginform.html", form=form)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect("/")


class DecimalEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, decimal.Decimal):
            return str(o)
        return super(DecimalEncoder, self).default(o)


@bp.route("/list_itens", methods=['GET', 'POST'])
def list_itens():
    # get request
    if request.method == 'GET':
        get_item = get_items()
        message_json = []
        for get_itens in range(len(get_item)):
            message_json.append({
                'nome': get_item[get_itens].name,
                'preco': format(get_item[get_itens].price, '.2f')
            }
            )
        print(message_json)
        return json.dumps(message_json)

flaskproject/src/templates/about.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block top %}
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1>CodeFoods</h1>
    </div>
  </div>
</section>
{% endblock %}

{% block main %}
<p>

  O melhor site de delivery
  de lanche do mundo! da twitch!
  e do universo!!!!

</p>
{% endblock %}

flaskproject/src/templates/base.html
<!DOCTYPE html>
<html>

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/responsive.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/index.js')}}"></script>
    {% endblock head %}

    {%block extra_css %} {% endblock extra_css %}
</head>

<body>


    {% block nav %}
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://bulma.io">
                <strong>Comilão Lanches</strong>
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="/">
                    Home
                </a>

                <a class="navbar-item" href="{{ url_for('site.lanches') }}">
                    Lanches
                </a>

                <a class="navbar-item" href="{{ url_for('site.about') }}">
                    Sobre
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        More
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item">
                            Pizza
                        </a>
                        <a class="navbar-item">
                            Pastel
                        </a>
                        <a class="navbar-item">
                            Hamburguer
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item">
                            Report an issue
                        </a>
                    </div>
                </div>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if current_user.is_authenticated %}
                        <a class="button is-light" href="{{url_for('site.logout')}}">
                            Logout
                        </a>
                        {% else %}
                        <a class="button is-primary" href="{{url_for('site.signup')}}">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-light" href="{{url_for('site.login')}}">
                            Log in
                        </a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% endblock nav %}

    {% block top %}
    {% endblock top %}

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning">
        <ul class="flashes">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% endwith %}

    <section class="section">
        <div class="container">
            {% block main %}

            {% endblock main %}
        </div>
    </section>

    {% block footer %}
    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
                <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
                is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
            </p>
        </div>
    </footer>
    {% endblock footer %}
</body>

</html>

flaskproject/src/templates/index.html
{% extends "base.html" %}
{% import "macros/list_item_index.html.j2" as list_item %}
{% block top %}
<section>
  <div class="header">
    <div class="header-content">
      <h1 class="nome">Bem vindo
          {% if current_user.is_authenticated %}
          {{ current_user.nome }}
          {% endif %}
      </h1>
    </div>
  </div>
</section>
{% endblock top %}

{% block main %}
<div class="columns">
  {{ list_item.cards(get_item) }}
</div>
{% endblock main %}

flaskproject/src/templates/lanches.html
{% extends "base.html" %}
{% import "macros/list_item.html.j2" as list_item %}
{% block top %}
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                {{ site_name }}
            </h1>
            <h2 class="subtitle">
                {{ site_subtitle }}
            </h2>
        </div>
    </div>
</section>
{% endblock top %}


{% block main %}
<div class="columns">
   {{ list_item.cards(get_item)}}
</div>
{% endblock main %}

flaskproject/src/templates/loginform.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block top %}
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1>Login</h1>
    </div>
  </div>
</section>
{% endblock %}


{% block main %}

<div class="oi">
  <form class='login-form' action='{{url_for("site.login")}}' method='post' enctype='multipart/form-data'>
    {{form.csrf_token}}
    <span class="title-login">Login</span>
    {{form.email.label}}
    {{form.email(class="label-email" ,size=30, placeholder="")}}

    {{form.password.label}}
    {{form.password(class="label-email", size=30)}}

    <input class="btnSignUp" type='submit' value='submit' onclick="logged()"/>
  </form>

{% endblock %}

flaskproject/src/templates/restaurants.html
{% extends "base.html" %}
{% import "macros/list_item.html.j2" as list_item %}
{% block top %}
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                {{ site_name }}
            </h1>
            <h2 class="subtitle">
                {{ site_subtitle }}
            </h2>
        </div>
    </div>
</section>
{% endblock top %}


{% block main %}
<div class="columns">
   {{ list_item.cards(get_item)}}
</div>
{% endblock main %}

flaskproject/src/templates/userform.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block top %}
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1>Cadastre-se</h1>
    </div>
  </div>
</section>
{% endblock %}

{% block main %}

<form class='user-form' action='{{url_for("site.signup")}}' method='post' enctype='multipart/form-data'>
    {{form.csrf_token}}  

    {{form.email.label}}<br>
    {{form.email(size=20)}}<br>

    {{form.password.label}}<br>
    {{form.password(size=20)}}<br>

    {{form.foto.label}}<br>
    {{form.foto}}<br> 

    <input type='submit' value='envie ai!!'/>
</form>

</form>


{% endblock %}